---
device:
  user_id: keichi
  type: sensor
  coordinate:
    longitude: 34.8222789
    latitude: 135.5258597
cpp:
  heartbeat_interval: 60
  base_url: http://localhost:8888/api
dpp:
  listen_address: 0.0.0.0
  listen_port: 51423
docker:
  base_url: tcp://localhost:1234
